set(CCppProperties "${CMAKE_SOURCE_DIR}/.vscode/c_cpp_properties.json")

if(EXISTS "${CCppProperties}")
    file(STRINGS "${CCppProperties}" lines ENCODING UTF-8 NEWLINE_CONSUME)
    list(LENGTH lines lineCount)

    set(file_str ${lines})
    # message(STATUS "${file_str}")
    if("${file_str}" MATCHES "\"includePath\": \\[[^\n]*(\r?\n?[ \t]*)")
        set(spacer ${CMAKE_MATCH_1})

        set(includes "")
        foreach(dir IN LISTS CONAN_INCLUDE_DIRS)
            string(APPEND includes "${spacer}\"${dir}\",")
        endforeach()

        string(REGEX REPLACE "(\"includePath\": \\[[^\n]*)" "\\1@includes@" new_str "${file_str}")
        string(CONFIGURE "${new_str}" new_str @ONLY)
        # message(STATUS "${new_str}")
        file(WRITE "${CCppProperties}" "${new_str}")
    endif()

    # foreach(i RANGE ${lineCount})
    #     list(GET lines ${i} line)
    #     if("${line}" MATCHES "([ \t]*).*\"includePath\": \\[.*")
    #         set(indent ${CMAKE_MATCH_1})
    #         if("${indent}" MATCHES "[\t]*")
    #             string(APPEND indent "\t")
    #         else()
    #             string(APPEND indent "    ")
    #         endif()
    #         math(EXPR pos "${i} + 1")

    #         foreach(dir IN LISTS CONAN_INCLUDE_DIRS)
    #             list(INSERT lines ${pos} "${indent}\"${dir}\",")
    #         endforeach()
    #         break()
    #     endif()
    # endforeach()

    # list(JOIN lines "\n" newLines)
    # message(STATUS "${newLines}")
    # file(WRITE "${CCppProperties}" "${newLines}")
endif()